server:
  name: "project-api"
  addr: "127.0.0.1:9000"
zap:
  debugFileName: "D:\\项目日志\\debug\\project-debug.log"
  infoFileName: "D:\\项目日志\\info\\project-info.log"
  warnFileName: "D:\\项目日志\\error\\project-error.log"
  maxSize: 500
  maxAge: 28
  MaxBackups: 3
etcd:
  addrs:
    - "127.0.0.1:2379"
redis:
  host: 101.43.166.179
  port: 6379
  password: "Bao1417165487"
  db: 0
mysql:
  addrs:
    - "127.0.0.1:3306"
  user: root
  password: Bao1417165487
  dbname: lxy
